import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  async function sendMails() {
    try {
      const ress = await axios.post("/api/sendmail", {});

      console.log(ress);
    } catch {}
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 onClick={sendMails}>SENDING MAILS</h1>
      </main>
    </div>
  );
}
