import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";
import { Input, Button, Heading } from "@chakra-ui/react";
export default function Home() {
  const [mail, setMail] = useState("");

  function inputHandler(e: React.ChangeEvent<HTMLInputElement>) {
    setMail(e.target.value);
  }

  async function sendMails() {
    try {
      const ress = await axios.post("/api/sendmails", {
        email: mail,
      });

      console.log(ress);
    } catch {}
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mail Sender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1">SENDING MAILS</Heading>
        <Input onChange={inputHandler} type="text" />
        <Button onClick={sendMails}>SEND MAIL</Button>
      </main>
    </div>
  );
}
